name: CI (Push)

on:
  push:
    branches-ignore:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: LexBorisoff/workflows/.github/workflows/ci.yml@main

  ci-results:
    name: CI Results (Push)
    if: always()
    needs: ci
    uses: LexBorisoff/workflows/.github/workflows/ci-results.yml@main
    with:
      ci-result: ${{ needs.ci.result }}
