name: CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches-ignore:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: LexBorisoff/workflows/.github/workflows/ci.yml@main

  ci-results:
    if: github.event_name == 'push'
    needs: ci
    uses: LexBorisoff/workflows/.github/workflows/ci-results.yml@main
    with:
      ci-result: ${{ needs.ci.result }}

  ci-results-pr:
    if: github.event_name == 'pull_request'
    needs: ci
    uses: LexBorisoff/workflows/.github/workflows/ci-results.yml@main
    with:
      ci-result: ${{ needs.ci.result }}
      name: CI Results (Pull Request)
